#!usr/bin/env bash
# script that will display information about subdomains
print_inf () {
	dig "$1" | grep -A1 "ANSWER SECTION:" | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2]
then
	print_inf "$2.$1"  "$2"
else
	print_inf "www.$1" "www"
	print_inf "lb-01.$1" "lb-01"
	print_inf "web-01.$1" "web.01"
	print_inf "web-02.$1" "web-02"
fi
