#!/usr/bin/env bash
# script that displays: To infinity and beyond and I am invincible

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM 
done
