#!/usr/bin/env bash
#displays Best School 10 times, and display hi in the 9th iteration.

i=0
while [ "$i" -lt 10 ]; do
	if [ "$i" -eq 8 ]; then
		echo "Best School"
		echo "hi"
	else
		echo "Best School"
	fi
	((i++))
done
